package com.citi.analytic.entity;

import com.citi.analytic.domain.Entity;

public class User implements Entity{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8439623844874210797L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAMOND.USER_ACCOUNT.USER_ID
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAMOND.USER_ACCOUNT.ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAMOND.USER_ACCOUNT.FIRSTNAME
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAMOND.USER_ACCOUNT.LASTNAME
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAMOND.USER_ACCOUNT.ADDRESS
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAMOND.USER_ACCOUNT.PASSWORD
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAMOND.USER_ACCOUNT.EMAIL
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAMOND.USER_ACCOUNT.PHONE
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAMOND.USER_ACCOUNT.ZIPCODE
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAMOND.USER_ACCOUNT.TYPE
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAMOND.USER_ACCOUNT.USER_ID
     *
     * @return the value of DIAMOND.USER_ACCOUNT.USER_ID
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAMOND.USER_ACCOUNT.USER_ID
     *
     * @param userId the value for DIAMOND.USER_ACCOUNT.USER_ID
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAMOND.USER_ACCOUNT.ACCOUNT
     *
     * @return the value of DIAMOND.USER_ACCOUNT.ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAMOND.USER_ACCOUNT.ACCOUNT
     *
     * @param account the value for DIAMOND.USER_ACCOUNT.ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAMOND.USER_ACCOUNT.FIRSTNAME
     *
     * @return the value of DIAMOND.USER_ACCOUNT.FIRSTNAME
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAMOND.USER_ACCOUNT.FIRSTNAME
     *
     * @param firstname the value for DIAMOND.USER_ACCOUNT.FIRSTNAME
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAMOND.USER_ACCOUNT.LASTNAME
     *
     * @return the value of DIAMOND.USER_ACCOUNT.LASTNAME
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAMOND.USER_ACCOUNT.LASTNAME
     *
     * @param lastname the value for DIAMOND.USER_ACCOUNT.LASTNAME
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAMOND.USER_ACCOUNT.ADDRESS
     *
     * @return the value of DIAMOND.USER_ACCOUNT.ADDRESS
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAMOND.USER_ACCOUNT.ADDRESS
     *
     * @param address the value for DIAMOND.USER_ACCOUNT.ADDRESS
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAMOND.USER_ACCOUNT.PASSWORD
     *
     * @return the value of DIAMOND.USER_ACCOUNT.PASSWORD
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAMOND.USER_ACCOUNT.PASSWORD
     *
     * @param password the value for DIAMOND.USER_ACCOUNT.PASSWORD
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAMOND.USER_ACCOUNT.EMAIL
     *
     * @return the value of DIAMOND.USER_ACCOUNT.EMAIL
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAMOND.USER_ACCOUNT.EMAIL
     *
     * @param email the value for DIAMOND.USER_ACCOUNT.EMAIL
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAMOND.USER_ACCOUNT.PHONE
     *
     * @return the value of DIAMOND.USER_ACCOUNT.PHONE
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAMOND.USER_ACCOUNT.PHONE
     *
     * @param phone the value for DIAMOND.USER_ACCOUNT.PHONE
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAMOND.USER_ACCOUNT.ZIPCODE
     *
     * @return the value of DIAMOND.USER_ACCOUNT.ZIPCODE
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAMOND.USER_ACCOUNT.ZIPCODE
     *
     * @param zipcode the value for DIAMOND.USER_ACCOUNT.ZIPCODE
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAMOND.USER_ACCOUNT.TYPE
     *
     * @return the value of DIAMOND.USER_ACCOUNT.TYPE
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAMOND.USER_ACCOUNT.TYPE
     *
     * @param type the value for DIAMOND.USER_ACCOUNT.TYPE
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }
}