package com.citi.analytic.dao.mapper;


import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.citi.analytic.entity.User;
import com.citi.analytic.entity.UserCriteria;

public interface UserMapper extends MybatisMapper<User, UserCriteria>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    int countByCriteria(UserCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    int deleteByCriteria(UserCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    List<User> selectByCriteria(UserCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    User selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    int updateByCriteria(@Param("record") User record, @Param("example") UserCriteria criteria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIAMOND.USER_ACCOUNT
     *
     * @mbggenerated Mon Jul 24 20:11:01 CST 2017
     */
    int updateByPrimaryKey(User record);
}